services:
  mongodb:
    image: mongo:7.0
    container_name: agropacayales-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: agropacayales_db
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: agropacayales-backend-webflux
    restart: always
    ports:
      - "5001:5001"
    environment:
      PORT: 5001
      MONGODB_URI: mongodb://mongodb:27017/agropacayales_db
    depends_on:
      - mongodb

volumes:
  mongodb_data:
