# kubectl apply -f axel-huapaya-10-secret.yml
# kubectl delete -f axel-huapaya-10-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: axel-huapaya-10-secret
  namespace: axel-huapaya-10-namespace
type: Opaque
data:
  MONGO_DATABASE: YWdyb3BhY2F5YWxlc19kYg==
  MONGO_URI: bW9uZ29kYitzcnY6Ly9heGVsaHVhcGF5YV9kYl91c2VyOmxpZGVyMjAyMUBjbHVzdGVyMC5veWs2b2dzLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
  SERVER_PORT: ODA4MQ==
  SPRING_PROFILES_ACTIVE: Y2xvdWQ=

# CONVERTIR A BASE64 CON PAGINA WEB
# https://base64.guru/converter

# CONVERTIR A BASE64 CON COMANDOS (Linux/Mac/Git Bash)
# echo -n "tu_valor_real" | base64
# echo "dmFsb3JfZW5fYmFzZTY0" | base64 --decode

# CONVERTIR A BASE64 CON POWERSHELL (Windows)
# [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("tu_valor_real"))